version: "3"
services:
  web:
    image: 192.168.1.70:5000/nodeswarm
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9191:9090"
    networks:
      - webnet
networks:
  webnet: